cip/CIP2015-09-15-STARTS-WITH-and-ENDS-WITH.adoc
This CIP has already been accepted.
=> Adds the STARTS WITH and ENDS WITH CIP

cip/CIP2015-10-03-State-visibility-between-clauses.adoc, cip/CIP2015-10-27-State-visibility-between-clauses.adoc
=> Adds state visibility CIP

tck/README.adoc, tck/features/Literals.feature
This commit adds a place for the TCK to exist, a readme to describe its
format, and one initial feature.
NOTE: Don't merge this until we've settled for a licensing solution.
=> Initialize the TCK

tck/README.adoc, tck/features/CineastDependant.feature, tck/features/CineastDependent.feature, tck/features/Create.feature, tck/features/Literals.feature, tck/features/MatchAcceptance.feature, tck/features/ReturnAcceptance.feature
- Adds all current feature files
- Transpose parameters in feature files to use only two columns
- Format all queries in feature files to follow Cypher style guide
- Updated readme
=> Update TCK description and content

LICENSE.txt, tck/features/CineastDependant.feature, tck/features/Create.feature, tck/features/Literals.feature, tck/features/MatchAcceptance.feature, tck/features/ReturnAcceptance.feature
Replace GPL headers in TCK feature files.
=> License with Apache2

grammar/basic-grammar.xml, grammar/cypher.xml, grammar/generated/Cypher.g4, grammar/generated/cypher.ebnf
* Removes `Statements` production
* Removes `Pragma` production
* Fixes several whitespace bugs
=> Grammar bugfixes

tck/README.adoc, tck/features/MergeNodeAcceptance.feature, tools/tck/src/main/scala/org/opencypher/tools/tck/constants/TCKErrorTypes.scala
- Introduce new error type
- Add constants for error details
=> Add scenario for `MERGE` which violates a single constraint

docs/style-guide.adoc
This is a stripped-down version of the style guide that the docs team had previously.
=> Add style guide

tck/features/MergeRelationshipAcceptance.feature, tools/tck/src/main/scala/org/opencypher/tools/tck/constants/TCKErrorTypes.scala
Add new error detail: `VariableAlreadyBound`.
=> Port MergeRelationshipAcceptanceTest to TCK

grammar/basic-grammar.xml, grammar/cypher.xml, tools/grammar/src/test/java/org/opencypher/tools/grammar/Antlr4ParserTest.java, tools/grammar/src/test/resources/cypher.txt, tools/tck/src/main/java/org/opencypher/tools/tck/parsing/FormatListener.java, tools/tck/src/main/java/org/opencypher/tools/tck/parsing/ResultsVerifier.java
Also fixes a few whitespace bugs in the grammar.
=> Test grammar using known Cypher queries

tck/features/PatternAcceptance.feature, tools/tck/pom.xml, tools/tck/src/main/scala/org/opencypher/tools/tck/FeatureFormatChecker.scala
- Allows more than one `When`/`Then` steps to be used, which is useful for some scenarios
- Also include scala sources in sources JAR
=> Port PatternAcceptance to the TCK

tck/features/ExpressionAcceptance.feature, tck/features/LargeIntegerEquality.feature
- Use more appropriate name for feature file
- Move odd test to feature with more similar context
=> Port CypherTypeAcceptance to the TCK

tck/features/ColumnNameAcceptance.feature, tools/tck/src/main/scala/org/opencypher/tools/tck/FeatureFormatChecker.scala
Allow certain scenarios to break code style.
=> Port ColumnNameAcceptance to TCK

tck/features/SyntaxErrorAcceptance.feature, tools/tck/src/main/scala/org/opencypher/tools/tck/constants/TCKErrorTypes.scala
Add two new error details:
- `UnknownFunction`
- `InvalidNumberLiteral`
=> Port SyntaxExceptionAcceptance to the TCK

tck/features/AggregationAcceptance.feature
Merging as @systay and I paired on this
=> Ensure elements in list are ordered so that test is stable

tck/features/MiscellaneousErrorAcceptance.feature, tck/features/SemanticErrorAcceptance.feature, tools/tck/src/main/scala/org/opencypher/tools/tck/constants/TCKErrorTypes.scala
Adds several new error details
=> Port ErrorMessagesTest to the TCK

docs/style-guide.adoc
- Add new section `Recommendations`
- Add rule for `SKIP` and `LIMIT`
- Add table of contents
- Add recommended file extension `.cypher`
=> Style guide improvements

tck/features/ReturnAcceptance2.feature, tools/tck/src/main/scala/org/opencypher/tools/tck/constants/TCKErrorTypes.scala
=> Port ReturnAcceptance to the TCK

tck/features/SetAcceptance.feature
This must only be merged when https://github.com/neo4j/neo4j/pull/7366 is merged
=> Port SetAcceptance to the TCK

tck/features/MergeNodeAcceptance.feature
This must also be merged: https://github.com/neo4j/neo4j/pull/7394
=> Removed FOREACH tests from the TCK

grammar/basic-grammar.xml, tools/grammar/src/test/resources/cypher.txt
=> Support range literals without dots

tck/features/OptionalMatch.feature, tck/features/TernaryLogicAcceptance.feature, tools/tck/src/main/scala/org/opencypher/tools/tck/validateCodeStyle.scala, tools/tck/src/test/scala/org/opencypher/tools/tck/validateCodeStyleTest.scala
@thobe feel free to merge as appropriate.
=> Add scenarios for verifying the open world assumption

cip/CIP2016-07-07-Type-conversion-functions.adoc, tck/features/EqualsAcceptance.feature, tck/features/ExpressionAcceptance.feature, tck/features/Functions.feature, tck/features/FunctionsAcceptance.feature, tck/features/SkipLimitAcceptance.feature
Suggests renaming `toInt()` to `toInteger()`, and addition of `toBoolean()`.
=> Add type conversion functions CIP

cip/1.accepted/CIP2015-05-13-EXISTS.adoc
=> EXISTS CIP

docs/style-guide.adoc
Restructure content into sections, based on type of formatting (rather than type of language construct).
=> Add styling rules for subquery `EXISTS`

grammar/basic-grammar.xml, grammar/cypher.xml, tools/grammar/pom.xml, tools/grammar/src/main/java/org/opencypher/tools/grammar/Antlr4.java, tools/grammar/src/test/java/org/opencypher/tools/grammar/Antlr4ParserTest.java, tools/grammar/src/test/java/org/opencypher/tools/grammar/Antlr4TestUtils.java, tools/grammar/src/test/resources/cypher.txt, tools/tck/pom.xml, tools/tck/src/main/scala/org/opencypher/tools/tck/FeatureFormatChecker.scala, tools/tck/src/main/scala/org/opencypher/tools/tck/validateQueryGrammar.scala, tools/tck/src/test/java/org/opencypher/tools/InitFunction.java, tools/tck/src/test/java/org/opencypher/tools/VerifyFeaturesTest.java, tools/tck/src/test/scala/org/opencypher/tools/tck/validateQueryGrammarTest.scala
There's a lot of valid queries present in the TCK. This PR adds integration tests that puts them all through the generated Antlr4 parser.
=> Test the grammar using all TCK queries

grammar/basic-grammar.xml, grammar/cypher.xml, tools/grammar/src/main/java/org/opencypher/tools/grammar/Antlr4Massager.java, tools/grammar/src/test/resources/cypher.txt
Also fixes a number of whitespace bugs and removes some (_very_) old syntax leftovers.
=> Add pattern comprehension to grammar

grammar/basic-grammar.xml
=> Rename expression rules to be more explanatory

cip/1.accepted/CIP2016-12-19-Reserved-keywords.adoc, grammar/basic-grammar.xml
Categorises reserved words into proper groups. Also adds five reserved words for future use: `MANDATORY`, `SCALAR`, `OF`, `ADD`, `DROP`.
=> Categorise reserved words

grammar/cypher.xml, tools/grammar/src/test/java/org/opencypher/tools/grammar/Antlr4ParserTest.java, tools/grammar/src/test/java/org/opencypher/tools/grammar/Antlr4TestUtils.java, tools/grammar/src/test/resources/cypher-error.txt, tools/grammar/src/test/resources/cypher.txt
- Enforce valid clause structure in the grammar
- Add namespace part to procedure names
Also fixes a few syntax bugs in the TCK.
=> Grammar improvements

tools/tck/src/main/scala/org/opencypher/tools/tck/api/Scenario.scala
=> Fix multiple evaluation of graph parameter

tck/features/Aggregation.feature
This contains several test for min and max with different types.
=> Adding a feature for Aggregation that, for now, tests min and max

tck/features/CreateAcceptance.feature, tck/features/ProcedureCallAcceptance.feature, tools/tck/src/main/scala/org/opencypher/tools/tck/SideEffectOps.scala, tools/tck/src/main/scala/org/opencypher/tools/tck/api/CypherTCK.scala
Also make error message point to the problematic feature/scenario
Builds on top of 1c8fda6 and 6abd25e
=> Fix side-effect handling and allow custom errors in tests

tck/features/MatchAcceptance.feature
#I99 I clarified the scenario names a bit and removed superfluous `value` properties. These are not terribly important changes, so definitely feel free to reject/ask for changes if the current ones don't fit your needs.
=> Clarify scenario names for tests collecting relationships

grammar/cypher.xml, tools/grammar/src/test/resources/cypher-error.txt, tools/grammar/src/test/resources/cypher.txt
Changes to the grammar that aims at describing query structure more explicit raised some issues like #253, #265
This PR aims at fixing those issues.
=> Correct grammar for multipart query

tck/features/ListOperations.feature
- Acceptance tests for list slice
- Covers valid and invalid ranges
- Ported from Cypher for Gremlin
=> TCK scenarios for list slices

cip/1.accepted/CIP2018-10-29-EXISTS-and-IS-NOT-NULL.adoc
[CIP](https://github.com/sherfert/openCypher/blob/CIP-exists-is-not-null/cip/1.accepted/CIP2018-10-29-EXISTS-and-IS-NOT-NULL.adoc)
=> Added CIP2018-10-29 EXISTS and IS NOT NULL

tools/tck-api/src/main/scala/org/opencypher/tools/tck/values/CypherValueParser.scala, tools/tck-api/src/test/scala/org/opencypher/tools/tck/CypherValueParserTest.scala
Allows backticks to be used in string values
=> Support escaping in string literals

cip/1.accepted/CIP2016-12-19-Reserved-keywords.adoc
- Adds `CALL`, `YIELD`, `MANDATORY` to Clauses list
- Adds `FROM`, `GRAPH` to list of future reserved words
=> Update reserved words list

tck/README.adoc
* see https://github.com/opencypher/openCypher/pull/369
Signed-off-by: Dwitry dwitry@users.noreply.github.com
=> Describe property naming

tools/tck-reporting/pom.xml, tools/tck-reporting/src/main/scala/org/opencypher/tools/tck/reporting/CountScenarios.scala, tools/tck-reporting/src/test/resources/org/opencypher/tools/tck/reporting/cucumber/foo/bar/Test.feature, tools/tck-reporting/src/test/resources/org/opencypher/tools/tck/reporting/cucumber/foo/bar/boo/Boo.feature, tools/tck-reporting/src/test/resources/org/opencypher/tools/tck/reporting/cucumber/foo/bar/boo/Test.feature, tools/tck-reporting/src/test/resources/org/opencypher/tools/tck/reporting/cucumber/foo/dummy/Dummy.feature, tools/tck-reporting/src/test/scala/org/opencypher/tools/tck/reporting/CountScenariosTest.scala
This improves the scenario counting tool `org.opencypher.tools.tck.reporting.CountScenarios`.
The output now shows the hierarchical structure of the counting groups, which includes the hierarchical structure of the feature categories.
For illustration, the output on the current state of the TCK looks as follows:
```
Total                                                         2009
| clauses                                                       51
| | create                                                      51
| | | Feature: Create1 - Creating nodes                          9
| | | Feature: Create2 - Creating relationships                 17
| | | Feature: Create3 - Interoperation with other clauses      12
| | | Feature: Create4 - Large Create Query                      2
| | | …
```
=> Improve scenario counting

tck/features/clauses/remove/Remove1.feature, tck/features/clauses/remove/Remove2.feature, tck/features/clauses/set/Set1.feature, tck/features/clauses/set/Set4.feature, tck/features/clauses/set/Set5.feature, tck/features/uncategorized/LabelsAcceptance.feature, tck/features/uncategorized/NullAcceptance.feature
This PR categorizes scenarios for the REMOVE clause.
It also makes a small revision to the categorization of the SET clause.
=> Categorize remove

tck/features/expressions/temporal/Temporal1.feature, tck/features/expressions/temporal/Temporal2.feature, tck/features/expressions/temporal/Temporal3.feature, tck/features/expressions/temporal/Temporal4.feature, tck/features/expressions/temporal/Temporal5.feature, tck/features/expressions/temporal/Temporal6.feature, tck/features/expressions/temporal/Temporal7.feature, tck/features/expressions/temporal/Temporal8.feature, tck/features/expressions/temporal/Temporal9.feature
This PR categorizes temporal functions. It also factors in all backgrounds. Otherwise, no scenarios have been changed.
Note that Temporal4 contains scenarios that test storage capabilities for temporal values. These could also be categorized under the CREATE clause. However, given that temporal may be considered as advanced functionality, it seems sensible to bundle all its aspects in one category.
=> Categorizes temporal functions

tck/features/expressions/map/Map5.feature, tck/features/uncategorized/FunctionsAcceptance.feature
@hvub
1. Renamed `Map4.feature`->`Map5.feature` and added `@NegativeTest` annotation to all scenarios there.
2. Added `Map4.feature` with `exists` function scenario on maps.
=> map exists

tck/features/clauses/create/Create1.feature
Thanks to @AviAvni for raising this issue in #431
=> Add missing node variable

tck/features/expressions/literals/Literals6.feature
=> Use correct style for expected map result

tck/features/expressions/quantifier/Quantifier1.feature, tck/features/expressions/quantifier/Quantifier2.feature, tck/features/expressions/quantifier/Quantifier3.feature, tck/features/expressions/quantifier/Quantifier4.feature
The categories created by this PR are empty, i.e. they do not contain any scenarios. However, from a categorization point of view it is valuable to have them.
=> Categorize quantifier expressions

tools/grammar/src/main/java/org/opencypher/tools/g4processors/BNFProcessor.java, tools/grammar/src/main/java/org/opencypher/tools/g4processors/G4Processor.java, tools/grammar/src/test/java/org/opencypher/tools/grammar/Antlr4ParserTest.java, tools/grammar/src/test/java/org/opencypher/tools/grammar/Antlr4TestUtils.java
Little improvement regarding the use of a deprecated class.
=> Remove use of deprecated antlr class
