opencypher/openCypher

tck/features/AggregationAcceptance.feature
tck/features/CineastDependent.feature
tck/features/Create.feature
tck/features/DeleteAcceptance.feature
tck/features/ExpressionAcceptance.feature
tck/features/Literals.feature
tck/features/MatchAcceptance.feature
tck/features/MergeNodeAcceptance.feature
tck/features/OrderByAcceptance.feature
tck/features/RemoveAcceptance.feature
tck/features/ReturnAcceptance.feature
tck/features/UnionAcceptance.feature

The tests are now more in line with the Cypher style guidelines, not to mention improving readability for some of the longer, more complex queries. 
Additionally, all queries now follow the multiline format.

Reformatted the TCK tests 

---

tck/README.adoc
tck/features/MergeNodeAcceptance.feature
tck/features/ReturnAcceptance.feature
tools/tck/src/main/scala/org/opencypher/tools/tck/FeatureFormatChecker.scala
tools/tck/src/main/scala/org/opencypher/tools/tck/constants/TCKStepDefinitions.scala
tools/tck/src/main/scala/org/opencypher/tools/tck/validateCodeStyle.scala
tools/tck/src/test/scala/org/opencypher/tools/tck/validateCodeStyleTest.scala

Removes support for the 'inline' format, and forces scenarios to use the multiline format. Also enforces space after comma and colon in the verification process (more complex rules are left for when more sophisticated analysis tools are available; the Cypher AST).
Update the readme, which was a bit obsolete.

Remove inline format

---

tck/features/WhereAcceptance.feature
tools/tck/src/main/scala/org/opencypher/tools/tck/constants/TCKErrorTypes.scala

Adds a new error detail `IncomparableValues`.

Port WhereAcceptance to the TCK

---

tck/features/LabelsAcceptance.feature
tools/tck/src/main/scala/org/opencypher/tools/tck/FeatureFormatChecker.scala
tools/tck/src/main/scala/org/opencypher/tools/tck/constants/TCKErrorTypes.scala
tools/tck/src/main/scala/org/opencypher/tools/tck/constants/TCKStepDefinitions.scala

Introduces the notion of a 'control query' - a query used to make additional assertions on the graph state after an updating query was executed. This is a more sophisticated extension to just asserting on the somewhat primitive side effects.

Port LabelsAcceptanceTest to the TCK

---

tck/features/VarLengthAcceptance.feature
tck/features/VarLengthAcceptance2.feature
tools/tck/src/main/scala/org/opencypher/tools/tck/constants/TCKErrorTypes.scala

Add new error detail `InvalidRelationshipPattern`.
The reason there are two files for this acceptance test is because one of the tests had a very different setup structure compared to the others. As the comments will tell you, in the long term the larger file should be refactored into using two named graphs instead of the large setup in the `Background` followed by the graph refactoring steps that certain scenarios have to do.

Port VarLengthAcceptance to the TCK

---

tck/features/SemanticErrorAcceptance.feature
tools/tck/src/main/scala/org/opencypher/tools/tck/constants/TCKErrorTypes.scala

Adds several new error details:
- UndefinedVariable
- VariableTypeConflict
- RelationshipUniquenessViolation
- CreatingVarLength
- InvalidParameterUse
- InvalidClauseComposition
- FloatingPointOverflow
- PropertyAccessOnNonMap
- InvalidArgumentExpression
- InvalidUnicode
- NonConstantExpression
- NoSingleRelationshipType
- InvalidAggregation

Port SemanticErrorAcceptance to the TCK

---

cip/CIP-Template.adoc

- Added a link to our grammar
- Ensured queries conform to our style guide
- Moved 'Examples' below 'Syntax' and 'Semantics'

Sundry edits to the CIP Template

---

grammar/README.adoc
grammar/basic-grammar.xml
grammar/commands.xml
grammar/cypher.xml
grammar/pre-parser.xml
grammar/start.xml
tools/grammar/src/main/java/org/opencypher/grammar/Container.java
tools/grammar/src/main/java/org/opencypher/grammar/Grammar.java
tools/grammar/src/main/java/org/opencypher/grammar/Node.java
tools/grammar/src/main/java/org/opencypher/grammar/NonTerminalNode.java
tools/grammar/src/main/java/org/opencypher/grammar/Production.java
tools/grammar/src/main/java/org/opencypher/grammar/ProductionNode.java
tools/grammar/src/main/java/org/opencypher/grammar/ProductionResolver.java
tools/grammar/src/main/java/org/opencypher/grammar/Root.java
tools/grammar/src/main/java/org/opencypher/grammar/Sequenced.java
tools/grammar/src/main/java/org/opencypher/tools/grammar/Antlr4Massager.java
tools/grammar/src/main/shell/launch.sh
tools/grammar/src/test/java/org/opencypher/tools/grammar/Antlr4ParserTest.java
tools/grammar/src/test/resources/cypher-legacy.txt
tools/grammar/src/test/resources/cypher.txt

The openCypher grammar should reflect which parts of the Cypher language
that are standardized. To allow tool authors to still write tools for the de facto
grammar used by the only known Cypher implementation (Neo4j), rules are
not removed, but marked.
The default use is to ignore legacy rules, but supplying an option
`-DINCLUDE_LEGACY="true"` (or set the java property directly) will include
legacy rules.

Mark non-standardized parts of the grammar as legacy

---

grammar/basic-grammar.xml
grammar/start.xml
tck/README.adoc
tck/features/DeleteAcceptance.feature
tck/features/ExpressionAcceptance.feature
tck/features/FunctionsAcceptance.feature
tck/features/KeysAcceptance.feature
tck/features/MatchAcceptance.feature
tck/features/MatchAcceptance2.feature
tck/features/OrderByAcceptance.feature
tck/features/ReturnAcceptance.feature
tck/features/TernaryLogicAcceptance.feature
tck/features/UnwindAcceptance.feature
tools/grammar/src/test/resources/cypher.txt

Replaces `{}` with `$` for parameters.

Update TCK and grammar with new parameter syntax

---

.gitignore

Just to make sure generated grammar artifacts don't show up in the "git status", nor in the repository.

gitignore: grammar/generated

---

grammar/basic-grammar.xml

Fixes opencypher/openCypher#131

Allow whitespace between PatternPart symbols of a MATCH clause.

---

grammar/basic-grammar.xml
tools/grammar/src/test/resources/cypher.txt

Grammar prohibits using whitespace in count(*) atom

---

tools/grammar/src/main/shell/launch.sh

to avoid pollution of generated files. See issue #141

Redirecting pushd/popd outputs to /dev/null

---

grammar/basic-grammar.xml
grammar/commands.xml
grammar/cypher.xml
grammar/pre-parser.xml
grammar/start.xml

Fixes opencypher/openCypher#140
Should be merged after opencypher/openCypher#138.
known bug: this creates weird thing in the railroad diagram (see image attached) as SP has rr:skip="true", but its optional routes are shown.

Rework whitespace handling in grammar not to include unnecessary ws nodes

---

cip/2.testable/CIP2015-09-15-STARTS-WITH-and-ENDS-WITH.adoc
tck/features/StartsWithAcceptance.feature

With the introduction of the thorough definition of comparability, we need to sort these operators in line to achieve consistency.

Align `CONTAINS` et al with comparability

---

tck/features/MatchingSelfRelationships.feature
tck/features/SimplePatternSemantics.feature

There is lots of confusion around how self-relationships (or loops) are
matched by patterns. These scenarios aim to outline how this is supposed
to work, and how it differs from simple relationship matching.

Add scenarios around pattern matching and self-loops

---

cip/1.accepted/CIP2016-12-19-Reserved-keywords.adoc

Cypher should specify a set of reserved words that may not be used as variables, parameters, or function names. This would make parsing the language simpler, make it harder to write particularly confusing statements, and is in alignment with how computer languages in general are specified.

Reserved words

---

cip/1.accepted/CIP2015-09-16-public-type-system-type-annotation.adoc

In the drafting of the Property Graph Model I found I wanted to define property values as being of the _scalar, concrete_ Cypher types, at which point I saw we lacked specifying the notion of abstractness for our types. This PR suggests adding them.

Introduce notion of abstract vs concrete types

---

tck/features/DeleteAcceptance.feature
tck/features/FunctionsAcceptance.feature
tck/features/RemoveAcceptance.feature
tck/features/ReturnAcceptance2.feature

I discovered there are duplicate scenario names. There were two reasons for this:
* some scenarios were duplicated
* some scenarios had an incorrect names - their name suggested that they should work, but their `Then` clause specified a compile/runtime error.
This PR eliminates duplicate scenarios and renames failing scenarios appropriately.

Eliminate duplicate scenarios names

---

docs/property-graph-model.adoc

Generated IDs for section headers and other referenceable content are fragile as they may change unexpectedly.
Explicitly assigned ID are more stable.

Use explicit IDs for longer-lived link targets

---

.gitignore

This is not a terribly important change, but it'd be useful for Eclipse users if the Gitignore file was prepared for Eclipse and the Scala IDE as well.

Add Eclipse-specific entries to gitignore

---

tools/tck/src/main/resources/FeatureResults.g4

I think `relationshipDesc` should handle `propertyMap`s similarly to the `nodeDesc` rule, i.e. it can have 0 or 1 `propertyMap`s, multiple (2+) `propertyMap`s are not allowed.

Only allow a zero or one propertyMaps for relationshipDesc

---

cip/1.accepted/CIP2016-06-14-Define-comparability-and-equality-as-well-as-orderability-and-equivalence.adoc
tck/features/PathEquality.feature

Undirected matching on self-relationships (aka loops) is tricky. #162 makes an effort to try and make explicit the intended semantics. This leaves paths in an ill-defined state, however. Consider the graph with one node and one relationship (to itself), and the following query:
```
MATCH p = ()--()
RETURN p
```
#162 states that only one row is to be returned (there's only one combination of node-rel-node available in the data graph). However, if paths are supposed to capture the direction in which they traverse relationships, then which path should be returned by this query: the one that traverses the relationship outgoing, or the one that does it incoming? It seems ill-defined.
In no other circumstance other than a self-relationship will the traversed direction matter.
Same idea as in …

Change definition of path equality

---

tck/features/AggregationAcceptance.feature
tck/features/ComparisonOperatorAcceptance.feature
tck/features/MatchAcceptance.feature
tck/features/UnwindAcceptance.feature

Some of the test scenarios were a bit inconsistent. When there's a `RETURN` but no records are produced,  assertion should still be made on the headers. 
Example:
```
Scenario: Handle aggregates inside non-aggregate expressions
Given an empty graph
When executing query:
"""
MATCH (a {name: 'Andres'})<-[:FATHER]-(child)
RETURN {foo: a.name='Andres', kids: collect(child.name)}
"""
Then the result should be empty
And no side effects
```
Now:
```
Scenario: Handle aggregates inside non-aggregate expressions
Given an empty graph
When executing query:
"""
MATCH (a {name: 'Andres'})<-[:FATHER]-(child)
RETURN {foo: a.name='Andres', kids: collect(child.name)}
"""
Then the result should be:
| {foo: a.name='Andres', kids: collect(child.name)} |
And no side effects
```

Add header for empty result sets. Fixes #214

---

tools/grammar/pom.xml
tools/pom.xml
tools/tck/pom.xml
tools/tck/src/main/java/org/opencypher/tools/tck/parsing/generated/FeatureResultsBaseListener.java
tools/tck/src/main/java/org/opencypher/tools/tck/parsing/generated/FeatureResultsLexer.java
tools/tck/src/main/java/org/opencypher/tools/tck/parsing/generated/FeatureResultsListener.java
tools/tck/src/main/java/org/opencypher/tools/tck/parsing/generated/FeatureResultsParser.java

This is in response to the grammar change made by #207.
Upgrade to Antlr 4.5.3.
NOTE: Latest Antlr version is 4.6, which adds target language support for C++, Go and Swift. Upgrading to it was not drop-and-go, but I've put it on the todo list.

Regenerate Anltr parser listener

---

tools/grammar/src/test/java/org/opencypher/tools/grammar/Antlr4ParserTest.java

Minor fix: replace path in ignored test. The relative path works in both Eclipse & IntelliJ and also Maven.

Replace absolute path with relative path

---

grammar/basic-grammar.xml
tck/features/ProcedureCallAcceptance.feature
tools/grammar/src/test/resources/cypher.txt

- Correctly use parentheses for in-query procedure call

Add namespace to procedure names

---

tools/tck/pom.xml

Java Cucumber does not like **default package** referencing features in classpath:
```java
@RunWith(Cucumber.class)
@CucumberOptions(
// features = {"classpath:."} - doesn't work
// features = {"classpath:/"} - doesn't work
// features = {"classpath:"} - doesn't work
features = {"classpath:features"}
)
public class TestAgainstOpenCypherTck {
//...
}
```
Cucumber does something like:
```java
import cucumber.runtime.io.ClasspathResourceLoader;
import cucumber.runtime.io.Resource;
@Test
public void temp() throws IOException {
String features = "classpath:features";
ClasspathResourceLoader resourceLoader = new ClasspathResourceLoader(getClass().getClassLoader());
for (Resource resource : resourceLoader.resources(features.replace("classpath:", ""), ".feature")) { …
```

Making feature files available for external tests

---

tck/README.adoc
tck/features/DeleteAcceptance.feature
tck/features/MergeNodeAcceptance.feature
tck/features/MergeRelationshipAcceptance.feature
tck/features/SetAcceptance.feature

At the 2nd oCIM, @szarnyasg presented the problem of unclearly defined side effects in the TCK, which is also discussed in #221. @szarnyasg also proposed a solution, which is largely implemented in this PR, with one notable amendment: properties are defined not only by their key and value, but also by the containing entity.
This PR aims to solve #221.

Clearly define the meaning of TCK side effects

---

tck/README.adoc
tck/features/DeleteAcceptance.feature
tck/features/LargeCreateQuery.feature
tck/features/MergeIntoAcceptance.feature
tck/features/MergeNodeAcceptance.feature
tck/features/MergeRelationshipAcceptance.feature
tck/features/ProcedureCallAcceptance.feature
tck/features/SetAcceptance.feature
tck/features/UnwindAcceptance.feature

This updates the side effects specification of many TCK scenarios, following the definitions from #236.
It is worth to note that the standard definition of the `labels` side effect metric measures the amount of distinct labels in the graph, and not the amount of nodes carrying these labels. This has the consequence that some queries that set or remove labels from nodes will not report any side effects at all, under certain circumstances. For example, this is a valid scenario:
```
Scenario: Setting an already existing label does not constitute a side effect
Given any graph
And having executed:
"""
CREATE (:A), (:B)
"""
When executing query:
"""
MATCH (b:B)
SET b:A
"""
Then the result should be empty
And no side effects
```
It is beyond the scope of this PR to change this, but it could be a …

Align side effects with standard definitions

---

tools/grammar/src/main/java/org/opencypher/tools/grammar/Antlr4.java
tools/grammar/src/main/java/org/opencypher/tools/grammar/BnfWriter.java
tools/grammar/src/main/java/org/opencypher/tools/grammar/ISO14977.java
tools/grammar/src/test/java/org/opencypher/tools/grammar/Antlr4Test.java
tools/grammar/src/test/java/org/opencypher/tools/grammar/Antlr4TestUtils.java

Uses the prefix `oC_` for all parser rules. Lexer rules are treated
differently by ANTLR and are not subject to the same kind of conflicts.
Fixes #251

Prefix Antlr4 parser rules to avoid target language keywords

---

tck/features/CreateAcceptance.feature
tools/tck/src/main/scala/org/opencypher/tools/tck/api/Scenario.scala

Builds on top of 1c8fda6
Either we should calculate side effects more precisely or only make the assertion on an empty graph. We opted for making the assertion on an empty graph as the easier short-term solution

Fix side effect

---

tck/features/Create.feature
tck/features/CreateAcceptance.feature
tck/features/LargeCreateQuery.feature

Step 'side effect' takes distinct labels. So, side affects assertion could be affected by existing graph (which could already have the label to be added). To eliminate that 'any graph' step was replaced with 'empty graph' step in scenarios asserting labels diff.

Existing graph affects labels diff in 'side effect' step:

---

tck/features/ReturnAcceptance.feature

Currently the test `ReturnAcceptanceTest.Limit to two hits` is ambiguous. 
It selects all nodes from a graph and then limits this set to two with out an explicit order. The expectation however tests for specific nodes to be return although every combination would be valid.
This PR splits the above test into two tests. One test returns a set of equal elements and limits this set. Another test is equal to the original one but introduces a specific order on the nodes.

TCK: Make 'LIMIT TO TWO HITS' test more explicit

---

grammar/basic-grammar.xml
tools/grammar/src/test/java/org/opencypher/tools/grammar/Antlr4TestUtils.java
tools/grammar/src/test/resources/cypher-error.txt
tools/grammar/src/test/resources/cypher.txt

The grammar used to allow mixing of property lookups and node labels
in a sequence. In reality, however, all property lookups perede all
the label constraints.
This grammar modification reflects the real structure.

oC grammar: make PropertyOrLabelsExpression more specific. Fixes #288

---

grammar/cypher.xml
tools/grammar/src/test/resources/cypher-error.txt
tools/grammar/src/test/resources/cypher.txt

This change allows any updating clause to begin a query (part).
A continuation from #300 
A multi-part query now follows this simple outline:
1. one or more of
a. zero or more reading clauses
b. zero or more updating clauses
c. a WITH clause
2. one SinglePartQuery

Grammar simplifications

---

tools/tck-api/src/main/scala/org/opencypher/tools/tck/api/CypherTCK.scala

The previous version led to problems when running on windows where file.separator equals "\\"
( getClass.getResource does not handle "\\" )

Fix faulty use of system default file separator

---

tools/tck-api/src/main/scala/org/opencypher/tools/tck/api/CypherTCK.scala
tools/tck-api/src/main/scala/org/opencypher/tools/tck/api/Scenario.scala
tools/tck-api/src/main/scala/org/opencypher/tools/tck/api/events/TCKEvents.scala
tools/tck-api/src/test/scala/org/opencypher/tools/tck/api/events/TCKEventsTest.scala

This change extends TCK tools Scala API with scenario execution events model. Extension makes possible to integrate external test reports (such as Cucumber report) via event listener. The model includes scenario steps that enables more detailed report to be created comparing to the current JUnit 5 report, that only shows results at scenario level.

Add TCK execution events to allow custom test report

---

tck/features/ExpressionAcceptance.feature
tck/features/ListOperations.feature
tck/features/ReturnAcceptance.feature
tck/features/ReturnAcceptance2.feature
tools/tck-api/src/test/scala/org/opencypher/tools/tck/api/events/TCKEventsTest.scala

@Mats-SX please review and merge when you can. 
The new file `ListOperations` fully subsumes the following two files in the neo4j repo: 
- `NullListAcceptanceTest` 
- `ListExpressionAcceptanceTest`
I will make a note to the Cypher Team that they delete these two files once this PR has been merged and a new milestone created.

List Operations TCK

---

upload-release.sh

The script would not work from the sub-directory.
Until this is fixed, it should live in the top-level.
This also fixes some small issues with the script.

Moved upload-release script to top level

---

grammar/basic-grammar.xml

This splits the StringListNullOperationExpression to subrules in the grammar to separate string, list and null operations.
I think this way of separation to subrules has no consequences on the operator precedences. @Mats-SX, @szarnyasg please take a look at it.
Should close #321

Split StringListNullOperationExpression to specific parts.

---

tools/tck-api/src/main/scala/org/opencypher/tools/tck/api/CypherTCK.scala

Parsing the tests with assumed default encoding while running on very different systems is not good enough

Making sure, that we explicitly specify the codec of the parsed features

---

grammar/basic-grammar.xml

We added the missing namespace for function names in the grammar. Please review.

Add namespace to function names

---

tck/features/TemporalCreateAcceptance.feature

Single values and arrays must be handled separately due to compatibility reasons.

Split up temporal storage tests

---

grammar/basic-grammar.xml

This is a correction to the semantical partitioning of operators in #321.
Thanks @Izhaki for raising this issue in https://github.com/opencypher/openCypher/pull/324#commitcomment-31161870.

Grammar: move the IN operator from string operators to the list operators

---

grammar/basic-grammar.xml

@Mats-SX I took a stab at updating the grammar to fix #340. Please review.

Mark extract and filter functions legacy in the grammar

---

cip/1.accepted/CIP2015-08-06-date-time.adoc
cip/1.accepted/CIP2016-06-14-Define-comparability-and-equality-as-well-as-orderability-and-equivalence.adoc

[CIP2015-08-06](https://github.com/thobe/openCypher/blob/date-time/cip/1.accepted/CIP2015-08-06-date-time.adoc)

CIP2015-08-06 Date and Time

---

tck/features/JoinAcceptance.feature

The second scenario is already covered by the first scenario, which is matching on a subset of nodes.
The second scenario is requires MERGE for the init query, i.e. requires openCypher implementers to implement at least a basic form of MERGE.

Align JoinAcceptance with filename and remove redundant test

---

grammar/cypher.xml
tools/grammar/src/test/resources/cypher-error.txt
tools/grammar/src/test/resources/cypher.txt

allow YIELD *
forbid YIELD -
editorial change in InQueryCall
Co-Authored-By: Mats Rydberg <mats@neotechnology.com>
Fixes #344

allow WHERE directly after YIELD

---

tck/features/ProcedureCallAcceptance.feature

This scenario was weird and unclear. One can only pass implicit arguments when no RETURN clause is used, thus the title did not match the actual test.
Fixes #345

Removed scenario with unclear goal.

---

tools/grammar/src/main/java/org/opencypher/grammar/Description.java
tools/grammar/src/main/java/org/opencypher/tools/grammar/Antlr4.java
tools/grammar/src/test/java/org/opencypher/tools/grammar/Antlr4ParserTest.java
tools/grammar/src/test/java/org/opencypher/tools/io/OutputTest.java
tools/tck-api/src/test/scala/org/opencypher/tools/tck/api/events/TCKEventsTest.scala

Building on windows failed because some of the grammar tools and tests of same assumed System.lineSeparator was \n. Corrected to use lineSeparator or println as appropriate
Also the separation of example cypher queries in a test needs to specify that file character set is UTF-8 if the System default is different
OutputTest combined 3 assertions into one method call, but the Windows compiler failed to find that method. Split into three calls

build on windows - avoid backslash n

---

cip/1.accepted/CIP2016-06-14-Define-comparability-and-equality-as-well-as-orderability-and-equivalence.adoc
tck/features/Comparability.feature
tck/features/EqualsAcceptance.feature
tck/features/OrderByAcceptance.feature
tools/tck-api/src/main/scala/org/opencypher/tools/tck/values/CypherValue.scala
tools/tck-api/src/main/scala/org/opencypher/tools/tck/values/CypherValueParser.scala
tools/tck-api/src/test/scala/org/opencypher/tools/tck/CypherValueParserTest.scala

The Neo4j Cypher team recently fixed that our implementation didn't follow the 2016-06-14 CIP regarding comparisons and equality with lists containing null. However, during the work we found the CIP more confusing than helpful so I have tried to clarify the relevant parts of it and increase the number of examples.

Clarification about null in lists in CIP2016-06-14

---

tck/features/OrderByAcceptance.feature
tck/features/SkipLimitAcceptance.feature

This corrects the wrong assertion that SKIP/LIMIT should succeed with
negative integers at runtime, to make it consistent with the compile
time behavior.
It adds more tests and asserts on the same behavior for floating point
numbers.

Correct wrong assertions for SKIP/LIMIT.

---

tck/features/FunctionsAcceptance.feature
tck/features/ListComprehension.feature
tck/features/ListOperations.feature

The lower() function and length() of a collection is deprecated and
will be removed in Neo4j 4.0.

Replace deprecated syntax in TCK tests.

---

tck/features/SemanticErrorAcceptance.feature

There is no mention of this being an invalid clause composition anywhere
in neo4j or opencypher except this scenario.
In Neo4j, we decided to simply support it after this issue has been
opened: https://github.com/neo4j/neo4j/issues/12252

Allow MATCH after OPTIONAL MATCH.

---

grammar/cypher.xml
tck/features/SkipLimitAcceptance.feature

- Avoid keywords in variable names
- Inline `DISTINCT` in `ReturnBody` and rename to `ProjectionBody`

Some small improvements

---

cip/1.accepted/CIP2016-06-14-Define-comparability-and-equality-as-well-as-orderability-and-equivalence.adoc
tck/features/Comparability.feature
tck/features/EqualsAcceptance.feature
tck/features/OrderByAcceptance.feature

This changes the definitions for equality and comparability such that
we have two basic definitions `=` and `<` and all other operators are
defined using those. This has the advantage that equality between
different types is now `false` instead of `null`.
This also changes equality and comparability around NaN to be compatible
with IEEE 754. The changes include that comparing (<, <=, >, >=) numbers
to NaN is always false, equality between a number and NaN is always
false and `<>` between a number and Nan is always true.
[Rendered version with the changes](https://github.com/sherfert/openCypher/blob/ineq/cip/1.accepted/CIP2016-06-14-Define-comparability-and-equality-as-well-as-orderability-and-equivalence.adoc)

Equality not defined from comparability. Changes around NaN.

---

tck/README.adoc

This is a minor PR to resolve two broken links in the TCK readme file.

Fix outdated links in TCK Readme

---

tools/tck-reporting/pom.xml
tools/tck-reporting/src/main/scala/org/opencypher/tools/tck/reporting/CountScenarios.scala

This just adds a tiny tool to count TCK scenarios.
At the moment it count scenarios by total, feature, and tags and outputs the counts to stdout.
It is meant to help review TCK categorization work, i.e. allow to easily check if the number of scenarios has changed.

Count scenarios

---

pom.xml
tools/grammar/pom.xml

The runtime and generator versions were different for a period.
This was later fixed; this removes the traces of that history.
Fixes #351

Consolidate ANTLR version in a single Maven property

---

tools/tck-api/src/main/scala/org/opencypher/tools/tck/api/CypherTCK.scala
tools/tck-api/src/main/scala/org/opencypher/tools/tck/api/Scenario.scala
tools/tck-api/src/test/resources/org/opencypher/tools/tck/foo/bar/boo/Test.feature
tools/tck-api/src/test/scala/org/opencypher/tools/tck/api/CategoriesTest.scala
tools/tck-reporting/src/test/java/org/opencypher/tools/tck/reporting/cucumber/CucumberReportAdapterTest.java

This pull request changes the TCK API to expose the category hierarchy of a scenario in the `Scenario` case class so that scenarios can be filtered, counted, reported, etc. by category. 
The `Scenario` case class gains a new field `category: List[String]` which lists top-down the category names of a scenario's feature file. Example: Any scenario from `clauses/match/Match1.feature` will have a list `List("clauses", "match")`.

Expose categories in TCK API

---

tck/features/uncategorized/ListOperations.feature

This PR fixes a the name of one scenario. The name was equal to the name of another scenario within the same feature file, which is not supposed to happen.

Fix duplicate scenario name

---

tck/features/uncategorized/ListOperations.feature
tools/tck-integrity-tests/src/main/scala/org/opencypher/tools/tck/FeatureFormatChecker.scala
tools/tck-integrity-tests/src/main/scala/org/opencypher/tools/tck/validateDuplicateNames.scala

This PR should be merged after [PR 401](https://github.com/opencypher/openCypher/pull/401). Otherwise the CI build will fail. 
The PR extend the feature format checker to validate whether a TCK scenario an unambiguous name. 
The scenario name is required to be unique within a feature file, except for scenarios resulting from a Scenario Outline.
Before PR 401, the TCK contained two scenario with an ambiguous name. PR 401 fixes that.
With this PR, the build fails if the TCK contains scenarios with unambiguous names.

Test for duplicate scenario names

---

tck/features/uncategorized/ColumnNameAcceptance.feature
tools/tck-api/src/main/scala/org/opencypher/tools/tck/api/CypherTCK.scala
tools/tck-api/src/main/scala/org/opencypher/tools/tck/constants/TCKTags.scala
tools/tck-integrity-tests/src/main/scala/org/opencypher/tools/tck/FeatureFormatChecker.scala

This PR adapts FeatureFormatChecker to not check code style if a scenario has a @withIntentionalStyleViolation tag. This allow to write scenarios with intentional code style violations (or work around limitation of the code style checker).
This PR replaces [PR 405](https://github.com/opencypher/openCypher/pull/405), which had a messed-up history.

Tag to switch off code style checker – cleaned up history

---

tools/tck-inspection/src/main/scala/org/opencypher/tools/tck/inspection/browser/web/BrowserPages.scala
tools/tck-inspection/src/main/scala/org/opencypher/tools/tck/inspection/browser/web/TckBrowserWeb.scala

This PR has two tiny usability tweaks to the TCK browser 
- In the browse view, it show the percentage of total number of scenario for each category
- On the main page, the path field is prefilled value with the relative path pointing to the TCK of the oC repo the browser was started from

Scenario count in percentage in tck browser

---

tck/features/expressions/temporal/Temporal10.feature

One feature file with scenarios on computing durations from temporal values was overlooked when temporal was categorized. This PR fixes this and adds these scenarios to the temporal category as an additional feature. The PR also rolls the background of the original feature file into the scenarios.

Categorize temporal 2

---

tck/index.adoc
tools/tck-inspection/pom.xml
tools/tck-inspection/src/test/scala/org/opencypher/tools/GenerateTCKIndexDoc.scala

The [tck/index.adoc](tck/index.adoc) is intended as repository documentation for the feature categories.
This PR adds [GenerateTCKIndexDoc](https://github.com/opencypher/openCypher/compare/master...hvub:create-tck-index-during-build?expand=1#diff-715e7bfab98083a2e2eda02bffafb292R44), which generates the tck/index.adoc based on folder structure and .feature files. It excludes the `uncategorized` and `precategorized` folders. The generation is fairly simple at the moment. However, it keeps tck/index.adoc uptodate, which no categorization step so far did. If it proofs to be useful, it is possible to improve the generation.
The PR also add [GenerateTCKIndexDocTest](https://github.com/opencypher/openCypher/compare/master...hvub:create-tck-index-during-build?expand=1#diff-715e7bfab98083a2e2eda02 …

Generator for tck/index.adoc

---

tck/features/expressions/conditional/Conditional1.feature
tck/features/expressions/conditional/Conditional2.feature
tck/features/uncategorized/FunctionsAcceptance.feature

This categorizes conditional operations. Where is just one scenario for COALESCE and no for CASE WHEN. Hence, fairly trivial PR.

Categorize conditional operations

---

tools/tck-inspection/src/main/scala/org/opencypher/tools/tck/inspection/browser/web/TckBrowserWeb.scala
tools/tck-inspection/src/main/scala/org/opencypher/tools/tck/inspection/util/CallingSystemProcesses.scala

This PR extends the TCK Browser to so that TCK PR can be directly browsed and diffed by their PR number.
Browsing a PR, shows PR merged into the repository's HEAD (`+refs/pull/<pr number>/merge`). Diffing a PR, diffs the merged PR against the HEAD. This greatly simplifies PR reviewing, particularly if multiple PR are in flight at the same time.

Browse and Diff TCK PRs by PR number

---

tck/features/expressions/graph/Graph10.feature
tck/features/expressions/graph/Graph5.feature
tck/features/expressions/graph/Graph6.feature
tck/features/expressions/graph/Graph7.feature
tck/features/expressions/graph/Graph8.feature
tck/features/expressions/graph/Graph9.feature
tck/features/expressions/map/Map3.feature
tck/features/expressions/map/Map4.feature

This PR is based on [PR444](https://github.com/opencypher/openCypher/pull/444) and should be merged after it.
The actual changes of this PR over 444 start with commit 4bcced6 and concern the addition of [Graph5.feature](tck/features/expressions/graph/Graph5.feature) with a few scenarios for label expressions on node and edge variables, i.e. expression of the form `n:Label`.
Note that scenario [Graph5.[2]](https://github.com/opencypher/openCypher/compare/master...hvub:categorize-label-expression?expand=1#diff-ed21ee603c458138d3adb56e7f63853bR57) is currently not valid in Cypher, hence, the `@ignore` tag. It may be activated by removing the tag, in case Cypher adopts label expressions for relationship variables in some future.

Categorize label expression

---

tck/features/useCases/triadicSelection/TriadicSelection1.feature

This PR categorizes scenarios from `TriadicSelection.feature`. These scenarios are not primarily language feature motivated, but rather formulated around a use case. It seems worthwhile to have a special category for such scenarios. Hence the scenarios are categorized under `/useCases/triadicSelection/TriadicSelection1.feature`. Otherwise, the change is straighforward.

Categorize triadic selection

---

tck/features/clauses/match/Match1.feature
tck/features/clauses/match/Match2.feature
tck/features/clauses/match/Match3.feature
tck/features/clauses/match/Match6.feature
tck/features/clauses/merge/Merge1.feature
tck/features/clauses/merge/Merge2.feature
tck/features/clauses/merge/Merge3.feature
tck/features/clauses/merge/Merge5.feature
tck/features/expressions/boolean/Boolean4.feature
tck/features/expressions/graph/Graph4.feature
tck/features/expressions/graph/Graph6.feature
tck/features/expressions/graph/Graph9.feature
tck/features/expressions/list/List11.feature
tck/features/expressions/list/List12.feature
tck/features/expressions/list/List5.feature
tck/features/expressions/list/List6.feature
tck/features/expressions/literals/Literals5.feature
tck/features/expressions/map/Map1.feature
tck/features/expressions/mathematical/Mathematical3.feature
tck/features/expressions/path/Path3.feature
tck/features/uncategorized/SemanticErrorAcceptance.feature
tools/tck-api/src/test/scala/org/opencypher/tools/tck/api/events/TCKEventsTest.scala

~This PR builds on #457 and should be merge subsequently.~
This PR focuses on categorizing scenarios of `SemanticErrorAcceptance.feature`.
On the side is adjust the feature names and scenarios name of the feature and scenarios touched anyway to improve the naming consistency. More alignment is necessary and to be done in subsequent PRs. This one does not aim at provide a completely consistent naming scheme.
A number of negative test have been generalized and extended. There is a net addition of 232 scnearios, which stem mostly from a few added scenario outlines, each with a long list of examples, cf. for instance [here](https://github.com/opencypher/openCypher/pull/458/files#diff-0c1d84990dd3a9b66b4ba24337f636a23f9dd70216475b26751ab18423b9a530R133-R257).

Categorize more negative scenarios

---

tck/features/clauses/call/Call3.feature

This PR removes the two scenarios Call3.[7] and Call3.[8], which are currently not covered the openCypher spec and are an forgotten and outdated artifact of the past.

Remove Call3.[7] and Call3.[8]

---

pom.xml
tools/grammar/src/test/java/org/opencypher/tools/grammar/Antlr4TestUtils.java
tools/tck-api/pom.xml
tools/tck-api/src/test/scala/org/opencypher/tools/tck/CypherValueParserTest.scala
tools/tck-api/src/test/scala/org/opencypher/tools/tck/TckTest.scala
tools/tck-api/src/test/scala/org/opencypher/tools/tck/api/CypherTCKTest.scala
tools/tck-api/src/test/scala/org/opencypher/tools/tck/api/ScenarioTest.scala
tools/tck-api/src/test/scala/org/opencypher/tools/tck/api/TCKApiTest.scala
tools/tck-api/src/test/scala/org/opencypher/tools/tck/api/events/TCKEventsTest.scala
tools/tck-api/src/test/scala/org/opencypher/tools/tck/values/CypherValueTest.scala
tools/tck-inspection/pom.xml
tools/tck-inspection/src/test/scala/org/opencypher/tools/GenerateTCKIndexDoc.scala
tools/tck-inspection/src/test/scala/org/opencypher/tools/tck/inspection/browser/cli/CountScenariosTest.scala
tools/tck-inspection/src/test/scala/org/opencypher/tools/tck/inspection/diff/GroupCollectionDiffTest.scala
tools/tck-inspection/src/test/scala/org/opencypher/tools/tck/inspection/diff/GroupDiffTest.scala
tools/tck-inspection/src/test/scala/org/opencypher/tools/tck/inspection/diff/ScenarioDiffTest.scala
tools/tck-integrity-tests/pom.xml
tools/tck-integrity-tests/src/main/scala/org/opencypher/tools/tck/FeatureFormatChecker.scala
tools/tck-integrity-tests/src/main/scala/org/opencypher/tools/tck/validateDuplicateNames.scala
tools/tck-integrity-tests/src/test/scala/org/opencypher/tools/tck/TckTestSupport.scala

Since the recent update of various dependencies and number of scalatest-based test where not executed during the maven build, which unfortunately went unnoticed for a bit.
This PR fixes this.
With one qualification, though:
The tests in `tools/tck-integrity-tests/src/test/scala/org/opencypher/tools/tck/`, which test the functional components of the `org.opencypher.tools.tck.FeatureFormatChecker` are not executed. The `junit-vintage-engine`, which is required to let the `FeatureFormatChecker` itself be executed as part of the `org.opencypher.tools.VerifyFeaturesTest`, ignore the scalatests with outputs such as:
```
Nov. 06, 2020 8:57:58 VORM. org.junit.vintage.engine.discovery.DefensiveAllDefaultPossibilitiesBuilder$DefensiveAnnotatedBuilder buildRunner
WARNING: Ignoring test class using …
```

Get scala tests to run

---

tck/features/expressions/boolean/Boolean4.feature

This PR adds negative test for invalid arguments of the boolean `NOT` operation.

add tests on invalid arguments for NOT

---

tck/features/clauses/set/Set4.feature
tck/features/clauses/set/Set5.feature
tck/features/expressions/comparison/Comparison1.feature
tck/features/expressions/map/Map3.feature
tck/features/expressions/map/Map4.feature
tck/features/expressions/null/Null3.feature

This PR follows up #464 with changing and augmenting TCK scenarios to reflect the behavior now clarified in the [CIP](https://github.com/sherfert/openCypher/blob/71f865baba103b54ad7bda72c360917c9c4ccc17/cip/1.accepted/CIP2015-09-16-public-type-system-type-annotation.adoc).

Scenarios for maps with null values

---

cip/1.accepted/CIP2015-09-16-public-type-system-type-annotation.adoc
cip/1.accepted/CIP2016-06-14-Define-comparability-and-equality-as-well-as-orderability-and-equivalence.adoc
tck/features/clauses/call/Call1.feature

The PR 
* changes procedure signatures in TCK scenarios that have return type `VOID` to return type `()` and 
* removes duplicate scenarios that result from this change.
Return type `VOID` to return type `()` do not have a semantics difference in openCypher at the moment. The [Call CIP](https://github.com/openCypher/openCypher/blob/master/cip/1.accepted/CIP2015-06-24-call-procedures.adoc) does not allow `VOID` as output signature. Hence, there is no point in keeping such scenarios.

Remove VOID from procedure signatures

---

tools/pom.xml
tools/tck-compatibility-tests/pom.xml
tools/tck-compatibility-tests/util/pom.xml
tools/tck-compatibility-tests/util/src/main/scala/org/opencypher/tools/tck/compatibility/AsyncScalaTests.scala
tools/tck-compatibility-tests/util/src/main/scala/org/opencypher/tools/tck/compatibility/DynamicJunitTests.scala
tools/tck-inspection/src/test/scala/org/opencypher/tools/tck/GenerateTCKIndexDoc.scala

**This PR builds on #468** 
Are very common thing when using the TCK is to run the TCK scenarios against an implementation for testing. 
This PR adds module `tck-compatibility-tests`, which provides support for this.
The submodule `util` provide two traits that spawn hierachical tests with the help of the `TckTree`, which reflect the TCK categories and features in a test tree:
* `org.opencypher.tools.tck.compatibility.AsyncScalaTests` spawns asynchronic scalatests
* `org.opencypher.tools.tck.compatibility.DynamicJunitTests` spawns JUnit tests
The intend is, to add one submodule per implementation that should be tested against during build. Such submodules will have to use public artifacts of the implementation they test. Currently, no implementation is ready in this regard. It is expected …

Compatibility testing

---

tck/features/clauses/merge/Merge1.feature
tck/features/clauses/merge/Merge5.feature
tck/features/clauses/set/Set1.feature
tck/features/expressions/list/List1.feature
tck/features/expressions/literals/Literals2.feature
tck/features/expressions/literals/Literals8.feature

**This PR builds on #477.**
The PR makes last fixes / adjustments to scenarios revealed necessary by running TCK against Neo4j. 
More specifically, the PR fixes error information of six @NegativeTest scenarios. In two is change a wrong error detail. In four is changes the phase where the error is detected, which is in principle too detailed specification for the TCK and probably needs to be removed in the longer run, anyway.

Scenario fixes for M16

---

tck/features/expressions/typeConversion/TypeConversion1.feature
tools/tck-api/src/main/scala/org/opencypher/tools/tck/api/CypherTCK.scala
tools/tck-api/src/main/scala/org/opencypher/tools/tck/api/Scenario.scala
tools/tck-api/src/main/scala/org/opencypher/tools/tck/api/groups/Group.scala
tools/tck-api/src/main/scala/org/opencypher/tools/tck/api/groups/TckTree.scala
tools/tck-api/src/test/resources/org/opencypher/tools/tck/Outline.feature
tools/tck-api/src/test/scala/org/opencypher/tools/tck/api/ScenarioTest.scala
tools/tck-api/src/test/scala/org/opencypher/tools/tck/api/TCKApiTest.scala
tools/tck-api/src/test/scala/org/opencypher/tools/tck/api/groups/GroupCanonicalOrderingTest.scala
tools/tck-api/src/test/scala/org/opencypher/tools/tck/api/groups/GroupTest.scala
tools/tck-api/src/test/scala/org/opencypher/tools/tck/api/groups/TckTreeTest.scala
tools/tck-inspection/src/main/scala/org/opencypher/tools/tck/inspection/browser/web/PageBasic.scala
tools/tck-inspection/src/main/scala/org/opencypher/tools/tck/inspection/diff/ScenarioDiff.scala
tools/tck-inspection/src/test/scala/org/opencypher/tools/tck/inspection/browser/cli/CountScenariosTest.scala
tools/tck-inspection/src/test/scala/org/opencypher/tools/tck/inspection/diff/GroupDiffTest.scala
tools/tck-inspection/src/test/scala/org/opencypher/tools/tck/inspection/diff/ScenarioDiffTest.scala
tools/tck-inspection/src/test/scala/org/opencypher/tools/tck/inspection/diff/TckTreeDiffTest.scala
tools/tck-integrity-tests/src/test/scala/org/opencypher/tools/tck/ValidateScenario.scala

(This PR is based on PR #478)
This PR extends the TCK API and related tools to support naming of examples in scenario outlines.
The PR modifies the `TypeConversion1.[5]` scenario outline to illustrate the facility:
```Gherkin
@NegativeTest
Scenario Outline: [5] `toBoolean()` on invalid types #Example: <exampleName>
Given any graph
When executing query:
"""
WITH [true, <invalid>] AS list
RETURN toBoolean(list[1]) AS b
"""
Then a TypeError should be raised at runtime: InvalidArgumentValue
Examples:
| invalid | exampleName |
| []      | list        |
| {}      | map         |
| 1       | integer     |
| 1.0     | float       |
```
The outline parameter `<exampleName>` does not contribute to the scenario other than modifying the name of the outline. Note that the parameter in the outline name …

Facilitate named examples in scenario outlines

---

tck/features/clauses/create/Create3.feature
tck/features/clauses/create/Create6.feature
tck/features/clauses/delete/Delete5.feature
tck/features/clauses/delete/Delete6.feature
tck/features/clauses/remove/Remove3.feature
tck/features/clauses/set/Set6.feature

This PR follows up https://github.com/neo4j/neo4j-documentation/pull/848 on the openCypher side in a generalized form. It adds scenarios that test that cardinality changes caused by `RETURN … SKIP`, `RETURN … LIMIT`, `WITH … WHERE`, and aggregation in `WITH` and `RETURN` after a `CREATE`, `DELETE`, `SET`, or `REMOVE` clause do not affect the side effects of these clauses. PR does not represent an openCypher specification change, but makes assumed semantics explicit in form of TCK scenarios.
The PR does deliberately does not address the same kind of test for `MERGE`.

Scenarios for persistence of side effects over subsequent cardinality changes

---

tck/features/clauses/create/Create1.feature

This simple PR adds two scenarios that test the `CREATE` clause for creating multiple nodes with overlapping label sets.

Scenarios for creating multiple nodes with overlapping label sets

---

tools/grammar-production-links/demoForm.html
tools/grammar-production-links/grammarLink.html
tools/grammar-production-links/index.adoc

This PR adds the tool `grammarLink.html` in `tools/grammar-production-links`, which provides the possibility to stably link a production by name in the link:../../grammar[openCypher grammar files] without hard-coding the line number. For more details the `index.adoc` in the same folder.

Link to grammar production

---

grammar/basic-grammar.xml
grammar/cypher.xml
tck/features/clauses/call/Call5.feature
tools/grammar/src/test/resources/cypher.txt

PR this is a reaction to #460.
According to the [CIP on CALL](https://github.com/opencypher/openCypher/blob/master/cip/1.accepted/CIP2015-06-24-call-procedures.adoc) standalone procedure calls allow `YIELD *` while in-query procedure calls do not allow it.
This PR encodes this rule for `YIELD *` in the grammar. It also adds two scenarios to the TCK that test the two cases of the rule.
In passing, the PR removes `<seq> ... </seq>` tags that are immediately contained in `<production ...> ... </production>` tags. Productions imply a sequence, hence, such `<seq> ... </seq>` tags are superfluous.

Fixing YIELD grammar

---

tck/features/clauses/return-orderby/ReturnOrderBy2.feature
tck/features/clauses/return-skip-limit/ReturnSkipLimit2.feature
tck/features/expressions/pattern/Pattern2.feature

TCK scenarios should check order if query ends with ORDER BY

Add missing results order check in tck scenarios

---

tck/features/expressions/quantifier/Quantifier1.feature
tck/features/expressions/quantifier/Quantifier10.feature
tck/features/expressions/quantifier/Quantifier11.feature
tck/features/expressions/quantifier/Quantifier12.feature
tck/features/expressions/quantifier/Quantifier2.feature
tck/features/expressions/quantifier/Quantifier3.feature
tck/features/expressions/quantifier/Quantifier4.feature
tck/features/expressions/quantifier/Quantifier5.feature
tck/features/expressions/quantifier/Quantifier6.feature
tck/features/expressions/quantifier/Quantifier7.feature
tck/features/expressions/quantifier/Quantifier8.feature
tck/features/expressions/quantifier/Quantifier9.feature

This PR adds scenarios for quantifier expressions to the respective features, specifically:
- scenarios for `none(...)` to `expression/quantifier/Quantifier1`,
- scenarios for `single(...)` to `expression/quantifier/Quantifier2`,
- scenarios for `any(...)` to `expression/quantifier/Quantifier3`, and
- scenarios for `all(...)` to `expression/quantifier/Quantifier4`.
For each quantifier, the scenarios test:
- quantifier behavior on empty list
- quantifier behavior on list containing booleans
- quantifier behavior on list containing integers
- quantifier behavior on list containing floats
- quantifier behavior on list containing strings
- quantifier behavior on list containing lists
- quantifier behavior on list containing maps
- quantifier behavior on list containing nodes
- quantifier …

Fill quantifier features

---

.github/workflows/pr_and_push_verification.yml
pom.xml
tools/pom.xml
tools/tck-api/pom.xml
tools/tck-api/src/main/scala/org/opencypher/tools/tck/SideEffectOps.scala
tools/tck-api/src/main/scala/org/opencypher/tools/tck/api/CypherTCK.scala
tools/tck-api/src/main/scala/org/opencypher/tools/tck/api/Result.scala
tools/tck-api/src/main/scala/org/opencypher/tools/tck/api/events/TCKEvents.scala
tools/tck-api/src/main/scala/org/opencypher/tools/tck/values/CypherValueParser.scala
tools/tck-api/src/main/scala_2.12/org/opencypher/tools/tck/api/events/Collections.scala
tools/tck-api/src/main/scala_2.13/org/opencypher/tools/tck/api/events/Collections.scala
tools/tck-api/src/test/scala/org/opencypher/tools/tck/api/groups/TckTreeTest.scala
tools/tck-compatibility-tests/util/pom.xml
tools/tck-compatibility-tests/util/src/main/scala/org/opencypher/tools/tck/compatibility/AsyncScalaTests.scala
tools/tck-inspection/pom.xml
tools/tck-inspection/src/main/scala/org/opencypher/tools/tck/inspection/util/CallingSystemProcesses.scala
tools/tck-integrity-tests/pom.xml
tools/tck-integrity-tests/src/test/scala/org/opencypher/tools/tck/ValidateSteps.scala
tools/tck-reporting/pom.xml
tools/tck-reporting/src/test/java/org/opencypher/tools/tck/reporting/cucumber/CucumberReportAdapterTest.java
tools/tck-reporting/src/test/resources/org/opencypher/tools/tck/reporting/cucumber/expected.json

* Add two maven profiles, `scala-212` and `scala-213` to build for Scala 2.12 or Scala 2.13, keeping the existing default of Scala 2.12. 
* Due to collection library incompatibilities between 2.12 and 2.13, tck-api requires a slightly different classpath for each, so I've added `scala_2.12` and `scala_2.13` additional source directories for this module. 
* Added additional maven plugins for the additional src directory and rewriting the Scala versions in the .poms
* Changed the output of the side effects reporting to make the order it displays additions and deletions consistent. This was previously unordered and behaving differently on 2.12 and 2.13, causing a test failure.
* Upgrade some dependencies to be compatible with 2.12 and 2.13

Add support for Scala cross building for 2.12 and 2.13

---

tools/tck-api/src/main/scala/org/opencypher/tools/tck/SideEffectOps.scala
tools/tck-api/src/test/scala/org/opencypher/tools/tck/TckTest.scala

To be able to find root cause when something fails during side effect measurement queries

Retain causing exception in MeasurementFailed

---

tools/tck-api/src/main/scala/org/opencypher/tools/tck/api/CypherTCK.scala
tools/tck-api/src/main/scala/org/opencypher/tools/tck/api/Scenario.scala
tools/tck-api/src/main/scala/org/opencypher/tools/tck/constants/TCKErrorTypes.scala
tools/tck-api/src/main/scala/org/opencypher/tools/tck/constants/TCKTags.scala
tools/tck-api/src/test/resources/org/opencypher/tools/tck/Foo.feature
tools/tck-api/src/test/scala/org/opencypher/tools/tck/api/TCKApiTest.scala

With this PR scenarios can specify error characteristics (error type, the error phase, the error details) with a wildcard in the ExpectedError step of a scenario.
The wildcards are used in a scenario as follows:
- **Any error type:** `Then a Error should be raised at ...: ...`
- **Any error phase:** `Then a ... should be raised at any time: ...`
- **Any error detail:** `Then a ... should be raised at ...: *`
Where a wildcard is given, the TCK API will not test the respective error characteristics on the error returned by an implementation for the respective scenario step. In other words, a scenario with an error characteristics wildcard cannot fail on this error characteristics in this ExpectedError step. The scenario may still fail 
- on other steps
- on other error characteristics that …

Add TCK error characteristics wildcards

---

tck/features/expressions/typeConversion/TypeConversion1.feature
tck/features/expressions/typeConversion/TypeConversion2.feature
tck/features/expressions/typeConversion/TypeConversion3.feature
tck/features/expressions/typeConversion/TypeConversion4.feature

This PR make minor improvement to type conversion function scenarios. The change is twofold:
1. It removes test on "invalid" argument type, which actually reasonable to accept
2. It harmonizes name and style of the invalid argument type scenarios across all four features

Fix type conversion scenarios

---

tck/features/expressions/list/List1.feature
tools/tck-integrity-tests/src/test/scala/org/opencypher/tools/tck/ValidateSteps.scala

This PR harmonizes scenarios in feature `List1` that check for invalid types in a list element access and relaxes the error details of this scenarios.
In passing this PR also fixes a bug in the step validation of the `TckScenarioFormatCheck` w.r.t. error detail wildcards.

Improve list access type checking scenarios

---

pom.xml
tools/tck-api/pom.xml
tools/tck-compatibility-tests/tck-compatibility-tests-util/pom.xml
tools/tck-inspection/pom.xml
tools/tck-integrity-tests/pom.xml
tools/tck-reporting/pom.xml

For the 2.13 cross build to work the Scala dependencies cannot be in the top level .pom as this will not work in a dependency hierarchy unless everything has a Scala version. To fix, move all the Scala dependencies under the scala modules so that the non-Scala modules can stay as they are. tck-reporting has direct Scala dependencies so no choice there.

Restructure Scala Dependencies

---

tck/features/expressions/boolean/Boolean5.feature

* This assertion was initially correct
* After some discussion we thought that it was wrong
* We now understand why it initially was correct (we missed that 'false AND null -> false')

Revert incorrect update to test assertion

---

grammar/basic-grammar.xml
tools/grammar/src/test/resources/cypher-error.txt
tools/grammar/src/test/resources/cypher.txt

The bug allowed arbitrarily many occurrences of `+` or `-` operators.
Only a single operator is allowed as part of this expression.
Since a literal expression also allows a preceding `-` character (for
a negative number literal), `--1` for example is also allowed.

Fix a bug in UnaryAddSubtractExpression

---

tools/tck-inspection/pom.xml
tools/tck-integrity-tests/pom.xml
tools/tck-integrity-tests/src/test/scala/org/opencypher/tools/tck/ScenarioFormatChecker.scala
tools/tck-integrity-tests/src/test/scala/org/opencypher/tools/tck/ValidateQuery.scala
tools/tck-integrity-tests/src/test/scala/org/opencypher/tools/tck/ValidateScenario.scala

This builds on PR #520.
The `TckScenarioFormatCheck` was set up to run tests in parallel, which however did not work. Unfortunately, it turned out that the parallel setup caused a massive amount of redundant execution. Looks like the check of every single scenario executed the ingestion of whole TCK, which makes scenario parsing quadratic in the number of scenarios — nothing promising with regards to execution speed. So that the `TckScenarioFormatCheck` end up needing over 20 minutes to check the TCK on a modern notebook computer.
Removing the parallel setup (a very simple code change) turned out to result in significantly faster execution of the `TckScenarioFormatCheck`. With this PR on the same computer, it checks the whole less than a minute.
Given that `TckScenarioFormatCheck` is part …

Speed up integrity tests

---

tools/tck-inspection/pom.xml
tools/tck-integrity-tests/pom.xml

Intellij has trouble identify dependencies of dependencies for runtime.
This PR adds these dependencies to the pom.

Fix dependencies after M18 for Intellij

---

tools/tck-api/src/main/scala/org/opencypher/tools/tck/values/CypherValue.scala
tools/tck-api/src/main/scala_2.12/org/opencypher/tools/tck/values/Hashing.scala
tools/tck-api/src/main/scala_2.13/org/opencypher/tools/tck/values/Hashing.scala
tools/tck-api/src/test/scala/org/opencypher/tools/tck/values/CypherValueTest.scala

On Scala 2.13, MurMurHash3 has changed it's contract to include the prefix in the hash calculation by default. This means that a CypherOrderedList and a CypherUnorderedList with the same content can be equal, but have different hashcodes. This breaks the equals / hashcode contract and is responsible for a TCK failure in Neo4j.
Unfortunately, the mechanism for including or excluding the prefix does not exist in Scala 2.12, so to ensure we can still cross build I have to pull out Scala API version specific calls to MurMurHash3.

Some CypherLists that are equal do not have the same hashcode

---

tck/features/clauses/match/Match4.feature
tck/features/clauses/return-orderby/ReturnOrderBy6.feature
tck/features/clauses/return/Return6.feature
tck/features/clauses/with-orderBy/WithOrderBy4.feature
tck/features/clauses/with/With6.feature
tools/tck-api/src/main/scala/org/opencypher/tools/tck/constants/TCKErrorTypes.scala

Expressions in WITH/RETURN/ORDER BY should not use implicit grouping keys.
In a RETURN/WITH expression that contains an aggregation or in a sort item where there is an aggregation in the preceding WITH/RETURN clause, the leaves of the expression must be one of:
- An aggregation
- A literal
- A Parameter
- Element property access on a variable - ONLY IF that property access is also a projection expression on its own
- Non nested static map access on a variable - ONLY IF that map access is also a projection expression on its own
- A variable - ONLY IF that variable is also a projection expression on its own (e.g. the n in RETURN n AS myNode, n.value + count(*))

Update and add tests with implicit grouping keys

---

cip/1.accepted/CIP2021-07-07-Grouping-keys-and-aggregation-expressions.adoc

This PR provides CIP that clarifies the semantics of grouping key and aggregation expressions in the WITH and the RETURN clause.
[Rendered view](https://github.com/hvub/openCypher/blob/CIP-on-grouping-keys-and-aggregation-expressions/cip/1.accepted/CIP2021-07-07-Grouping-keys-and-aggregation-expressions.adoc).

CIP on grouping keys and aggregation expressions

---

tck/features/expressions/list/List6.feature

Examples 1 to 7 use pattern predicates that introduce variables, which is forbidden (see below). https://github.com/opencypher/openCypher/blob/b0ea6c0de107cf0a9ff27d395adcb07d0baf492a/tck/features/expressions/pattern/Pattern1.feature#L197-L221
To avoid returning a `UndefinedVariable` (in adhearance with above scenario), I suggest we simply avoid introducing new variables in this scenario.

Update scenario to avoid illegally introducing variable in pattern predicate

---

tck/features/clauses/merge/Merge1.feature
tck/features/clauses/merge/Merge2.feature
tck/features/clauses/merge/Merge3.feature
tck/features/clauses/set/Set3.feature
tck/features/expressions/graph/Graph3.feature

We don't guarantee any ordering of the array returned by the `labels` function, right? These assertions causes failures in  https://github.com/neo-technology/neo4j/pull/17164.

Fix test assertions of labels function

---

tools/tck-api/src/main/scala/org/opencypher/tools/tck/values/CypherValue.scala
tools/tck-api/src/main/scala_2.12/org/opencypher/tools/tck/values/OrderingCompatibility.scala
tools/tck-api/src/main/scala_2.13/org/opencypher/tools/tck/values/OrderingCompatibility.scala
tools/tck-api/src/test/scala/org/opencypher/tools/tck/values/CypherValueTest.scala

Fix a bug where comparison of nodes was incorrect because of labels appearing in different order.
Causes failures in https://github.com/neo-technology/neo4j/pull/17164.

Fix bug in node comparison

---

tck/features/expressions/temporal/Temporal2.feature

Update to reflect timezone offset change to Europe/Stockholm in recent zoneinfo file. Arguably, it may be better to just remove this test, I would also be open to that.

Update for zoneinfo 2022b

---

tck/features/expressions/existentialSubqueries/ExistentialSubquery2.feature

This test is currently incorrect, when m is the grouping key, the max numConnections can be is 2, and not 3

Update to use n as the grouping key, instead of m in Exists Aggregation Acceptance test

---

cip/1.accepted/CIP2021-08-10-Operator-precedence.adoc
grammar/basic-grammar.xml

**This PR is based on #541.**
This PR proposes changes to the openCypher grammar for allowing chaining of non-arithmetic operators as a reaction to issue #539. With the PR, the grammar allows for instance 
```
RETURN foo()[1]:F, foo().x.y[1][4].name:F
```
as valid syntax, which was not the case before.
The PR also adjusts [CIP2021-08-10 Operator precedence](https://github.com/opencypher/openCypher/blob/master/cip/1.accepted/CIP2021-08-10-Operator-precedence.adoc) ([rendered view](https://github.com/hvub/openCypher/blob/chaining-of-non-arithmatic-operators/cip/1.accepted/CIP2021-08-10-Operator-precedence.adoc)) to the changed grammar.

Chaining of non arithmetic operators

---

tools/tck-api/src/main/scala/org/opencypher/tools/tck/api/Result.scala
tools/tck-api/src/test/scala/org/opencypher/tools/tck/api/CypherValueRecordsTest.scala

Fix bug in `CypherValueRecords.equalsUnordered` where rows with equal hash code could generate false negatives.

Fix bug in unordered rows comparison

---

tck/features/clauses/return-orderby/ReturnOrderBy6.feature
tck/features/clauses/with-orderBy/WithOrderBy4.feature

Background:
When referring to a concrete variable in an aggregation expresion in ORDER BY, e.g. referring to `you` in
```
WITH count(you.age) AS agg
ORDER BY me.age + count(you.age)
```
there are 2 errors:
* `you` is not in scope ("UndefinedVariable")
* It is not OK to use an aggregation function in ORDER BY ("AmbiguousAggregationExpression")
We are changing the way of our SemanticAnalysis such that the first error takes precedence.

Update expected errors in TCK

---

tools/tck-api/src/main/scala/org/opencypher/tools/tck/api/CypherTCK.scala
tools/tck-api/src/test/resources/org/opencypher/tools/tck/FailureWithSideEffects.feature
tools/tck-api/src/test/scala/org/opencypher/tools/tck/FailureWithSideEffectsTckTest.scala

Enables asserting on side effects in failing queries. This is useful for `CALL ... IN TRANSACTIONS` queries, that will fail but also have side effects.

Support expected errors with side effects

---

tools/tck-api/src/main/scala/org/opencypher/tools/tck/values/CypherValue.scala
tools/tck-api/src/test/resources/org/opencypher/tools/tck/FailureWithSideEffects.feature
tools/tck-api/src/test/scala/org/opencypher/tools/tck/FailureWithSideEffectsTckTest.scala
tools/tck-api/src/test/scala/org/opencypher/tools/tck/api/CypherValueRecordsTest.scala
tools/tck-api/src/test/scala/org/opencypher/tools/tck/values/CypherValueTest.scala

Fix bug in Cypher unordered list comparison. 
For example, assertions like this
```
Then the result should be (ignoring element order for lists):
| foo                 |
| ['Bob', 'Carl']     |
| ['Ada', 'Danielle'] |
| ['Danielle']        |
| ['Carl']            |
| []                  |
```
would fail even if the results were correct:
```
...failed with message: 
Expected (in any order of rows):
| foo |
| ['Bob', 'Carl'] |
| ['Ada', 'Danielle'] |
| ['Danielle'] |
| ['Carl'] |
| [] |
Actual:
| foo |
| ['Carl', 'Bob'] |
| ['Ada', 'Danielle'] |
| ['Danielle'] |
| ['Carl'] |
| [] |
```
Trello: https://trello.com/c/m36sEKjr

Fix bug in comparison of unordered lists

---

tools/tck-api/src/main/scala/org/opencypher/tools/tck/values/CypherValue.scala
tools/tck-api/src/test/scala/org/opencypher/tools/tck/api/CypherValueRecordsTest.scala
tools/tck-api/src/test/scala/org/opencypher/tools/tck/values/CypherValueTest.scala

Another bug fix uncovered this bug and led to TCK test failures when bumping TCK version in neo4j.

Fix bug in TCK row comparison
